site_name: Nentropic Research
site_description: An extension of the Graph Representation work
site_author: Nentropic Research
site_url: https://nentropic.dev

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - mkdocstrings
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
  - tags
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Documentation:
      - Getting Started: getting-started.md
      - API Reference: api-reference.md
  - About
  - Blog:  
    - Research Blog: blog/index.md
    - Technical Blog: tech-blog/index.md
  - Experiments:
      - Weights and Biases: https://www.wandb.ai/nentropic-research
      - Neptune.ai: https://www.neptune.ai
      - MIT GraphProcessing Baseline: experiments/mit_base.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-discord



markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

copyright: Copyright &copy; 2024 Nentropic Research

repo_name: yourusername/ephemegraphs
repo_url: https://github.com/Nentropic-0x0/ephemegraphs
edit_uri: edit/main/docs/
